---
- name: Process credentials for users in realm {{ tenant.name }}
  ansible.builtin.include_tasks: process_single_user_credentials.yml
  loop: "{{ tenant.users }}"
  loop_control:
    loop_var: user
    label: "{{ user.username }}"
