---
- name: Reconcile users
  ansible.builtin.include_tasks: reconcile_multiple_users.yml

- name: Reconcile roles for users
  ansible.builtin.include_tasks: reconcile_multiple_users_roles.yml

- name: Process credential reset and email notifications
  ansible.builtin.include_tasks: process_multiple_users_credentials.yml
