---
- name: Process credentials for users in realm {{ tenancy.name }}
  ansible.builtin.include_tasks: process_single_user_credentials.yml
  loop: "{{ tenancy.users }}"
  loop_control:
    loop_var: user
    label: "{{ user.email }}"
