---
- name: Resolve reconciled user context for {{ user.email }}
  ansible.builtin.set_fact:
    current_user_context: "{{ reconciled_users[tenancy.name ~ '/' ~ user.email] }}"

- name: Resolve any initial login action requirements for {{ user.email }}
  ansible.builtin.set_fact:
    required_actions: "{{ user.initial_login_actions | default(tenancy.defaults.initial_login_actions) }}"

- name: Determine if initial login email should be sent for {{ user.email }}
  ansible.builtin.set_fact:
    send_email: >-
      {{
        current_user_context.is_new_user | bool
        and current_user_context.enabled | bool
        and required_actions | length > 0
      }}

- name: Ensure any initial login action requirements configured for new user {{ user.email }}
  middleware_automation.keycloak.keycloak_user:
    auth_keycloak_url: "https://{{ iam_ingress_hostname }}"
    auth_realm: "{{ tenancy.name }}"
    auth_client_id: "{{ iam_client_id }}"
    auth_username: "{{ iam_tenant_admin_username }}"
    auth_password: "{{ iam_tenant_admin_password }}"
    realm: "{{ tenancy.name }}"
    username: "{{ user.username | default(user.email) }}"
    required_actions: "{{ required_actions }}"
    state: present
    validate_certs: true
  when: current_user_context.is_new_user and required_actions | length > 0

- name: Send out email for new user {{ user.email }}
  middleware_automation.keycloak.keycloak_user_execute_actions_email:
    auth_keycloak_url: "https://{{ iam_ingress_hostname }}"
    auth_realm: "{{ tenancy.name }}"
    auth_client_id: "{{ iam_client_id }}"
    auth_username: "{{ iam_tenant_admin_username }}"
    auth_password: "{{ iam_tenant_admin_password }}"
    realm: "{{ tenancy.name }}"
    username: "{{ user.username | default(user.email) }}"
    actions: "{{ required_actions }}"
    lifespan: 1036800
  when: send_email
