---
- name: Get token for Keycloak API requests auth
  ansible.builtin.uri:
    url: "https://{{ iam_ingress_hostname }}/realms/{{ tenancy.name }}/protocol/openid-connect/token"
    method: POST
    headers:
      Content-Type: "application/x-www-form-urlencoded"
    body: "username={{ iam_tenant_admin_username }}&password={{ iam_tenant_admin_password }}&grant_type=password&client_id=admin-cli"
    status_code: 200
  register: keycloak_token

- name: Process credentials for users in realm {{ tenancy.name }}
  ansible.builtin.include_tasks: process_single_user_credentials.yml
  loop: "{{ tenancy.users }}"
  loop_control:
    loop_var: user
    label: "{{ user.email }}"
