---
- name: Resolve reconciled user context for {{ user.email }}
  ansible.builtin.set_fact:
    current_user_context: "{{ reconciled_users[tenancy.name ~ '/' ~ user.email] }}"

- name: Determine if password reset email should be sent for {{ user.email }}
  ansible.builtin.set_fact:
    send_email: >-
      {{
        current_user_context.is_new_user | bool
        and current_user_context.enabled | bool
      }}

- name: Ensure initial login action requirements are set for {{ user.email }}
  community.general.keycloak_user:
    auth_keycloak_url: "https://{{ iam_ingress_hostname }}"
    auth_realm: "{{ tenancy.name }}"
    auth_username: "{{ iam_tenant_admin_username }}"
    auth_password: "{{ iam_tenant_admin_password }}"
    realm: "{{ tenancy.name }}"
    username: "{{ user.username | default(user.email) }}"
    required_actions: "{{ user.initial_login_actions | default(tenancy.defaults.initial_login_actions) }}"
    state: present
    validate_certs: true
  when: current_user_context.is_new_user

- name: Process and log email send out
  when: send_email
  block:
    - name: Send out email for {{ user.email }}
      ansible.builtin.uri:
        url: "https://{{ iam_ingress_hostname }}/admin/realms/{{ tenancy.name }}/users/{{ current_user_context.user_id }}/execute-actions-email"
        method: PUT
        headers:
          Content-Type: application/json
          Authorization: "Bearer {{ keycloak_token.json.access_token }}"
        body_format: json
        status_code:
          - 204
        validate_certs: true
      when: send_email

    - name: Log email send out for {{ user.email }}
      ansible.builtin.debug:
        msg: >-
          Initial login action requirement email {{ 'sent' if send_email else 'NOT sent' }}
          for user '{{ user.email }}' in realm '{{ tenancy.name }}'.

    - name: Throttle to prevent overload of Keycloak's SMTP
      ansible.builtin.pause:
        seconds: 0.2
      when: send_email
