---
- name: Get token for Keycloak API requests authorization
  ansible.builtin.uri:
    url: "https://{{ iam_ingress_hostname }}/realms/{{ tenancy.name }}/protocol/openid-connect/token"
    method: POST
    headers:
      Content-Type: "application/x-www-form-urlencoded"
    body: "username={{ iam_tenant_admin_username }}&password={{ iam_tenant_admin_password }}&grant_type=password&client_id={{ iam_client_id }}"
    status_code: 200
  register: keycloak_api_token
  no_log: true

- name: Reconcile roles for users in realm {{ tenancy.name }}
  ansible.builtin.include_tasks: reconcile_single_user_roles.yml
  loop: "{{ tenancy.users }}"
  loop_control:
    loop_var: user
    label: "{{ user.email }}"
