- name: Input validation
  hosts: localhost
  connection: local
  gather_facts: false

  tasks:
    - name: Detect if input vars were already included
      set_fact:
        has_loaded_tenancy_vars: "{{ tenancy is defined and tenancy.keys() | length > 0 }}"

    - name: Include inputs vars (if not included already)
      ansible.builtin.include_vars:
        file: ./vars/inputs.yml
        name: tenancy
      when: not has_loaded_tenancy_vars

    - name: Validate included vars (if not validated already)
      ansible.utils.validate:
        data: "{{ tenancy }}"
        criteria:
          - "{{ lookup('file',  './vars/inputs.schema.json') | from_json }}"
        engine: ansible.utils.jsonschema
      when: not has_loaded_tenancy_vars

    - name: Extract attributes from key at the root of the schema
      set_fact:
        tenancy: "{{ tenancy.tenancy }}"
